import { DM_Sans } from 'next/font/google'

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dm-sans',
})

export default function Footer() {
  return (
    <footer className={`bg-[#8B5E3C] text-white py-6 ${dmSans.variable} font-sans`}>
        <div className="p-4 border-t border-gray-200 text-center text-xs text-gray-900 mt-auto">
          <p>System and Software generated by Muhammad Hassan Jaffer</p>
        </div>
      {/* <div className="max-w-6xl mx-auto px-4">
        <div className="flex flex-col md:flex-row justify-between items-center">
          <div className="mb-4 md:mb-0">
            <p className="text-sm">
              &copy; {new Date().getFullYear()} Work Order Management System. All rights reserved.
            </p>
          </div>
          
          <div className="flex flex-col items-center md:items-end">
            <p className="text-xs mb-1">System Version: 1.0.0</p>
            <p className="text-xs font-light italic">
              Software generated by Muhammad Hassan Jaffer
            </p>
          </div>
        </div> */}

        {/* <div className="mt-4 pt-4 border-t border-white/20 text-center">
          <p className="text-xs">
            This proprietary software is protected under international copyright laws.
          </p>
        </div>
      </div> */}
    </footer>
  )
}